### ISSUE TITLE
Bug on ng9 

### ISSUE THREAD

**Issue by vlio20** [mattlewis92/angular-resizable-element#118]
For some reason the resizable item is bumping back to it's original size.

https://stackblitz.com/edit/angular-fbmklb

**Comment by mattlewis92** [comment]
Hey there, the directive doesn't actually save any of the changes itself, it's up to you to do that via the `resizeEnd` output like in the demo: https://github.com/mattlewis92/angular-resizable-element/blob/master/demo/demo.component.ts#L108-L116
