### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by pradeeprajr93** [mattlewis92/angular-resizable-element#25]
I can't even notice cursor change when I hover the resizable div. 
Kindly help. I'm using latest version of Angular 2.

**Comment by mattlewis92** [comment]
Without you sharing any code I can't say for sure, but I'm guessing you're missing `[resizeEdges]="{bottom: true, right: true, top: true, left: true}"` to enable resizing (by default the element is not resizable). I've updated the example in the readme to make this a bit more obvious.
