### ISSUE TITLE
NPM page links broken

### ISSUE THREAD

**Issue by jtc10005** [mattlewis92/angular-resizable-element#26]
Two links on your npm readme page are broken.
![image](https://cloud.githubusercontent.com/assets/16569775/20394089/f0730afe-aca3-11e6-85fd-1d7770ac2a9e.png)

**Comment by mattlewis92** [comment]
Ah you're looking at the old deprecated module name, please refer to the new package: https://www.npmjs.com/package/angular-resizable-element

**Comment by jtc10005** [comment]
Ah.  Got it.  You may want to consider marking the old one as depreciated and redirect to the new?

**Comment by mattlewis92** [comment]
It is, npm just doesn’t display anything on their site when a package is deprecated.


Kind regards,
Matt Lewis

**Comment by mattlewis92** [comment]
<img width="778" alt="screen shot 2016-11-17 at 15 15 31" src="https://cloud.githubusercontent.com/assets/6425649/20394856/e3c01380-acd8-11e6-96f3-3214800943d7.png">
