### ISSUE TITLE
Add a resize container option

### ISSUE THREAD

**Issue by mattlewis92** [mattlewis92/angular-resizable-element#30]
Allow passing a html element that only allows an element to be resized inside of this area

**Comment by mattlewis92** [comment]
Can be implemented via the validateResize input

**Comment by patrickoneill46** [comment]
Hi, am I missing something. In my validate function I want to validate against a parent rect which I am storing as a property in a component. However, in the validate function the 'this' context refers to the resize event, not my component context.

**Comment by mattlewis92** [comment]
The directive doesn't have access to the parent component class context, thus you'll need to bind the function yourself:
```
constructor() {
  this.validateResize = function() {
    // `this` should now be accessible
  }.bind(this);
}
```

**Comment by patrickoneill46** [comment]
thank you for getting back so quickly. Worked perfectly. Thanks
