### ISSUE TITLE
When ghostResize, clonedNode doesn't have height until mousemove

### ISSUE THREAD

**Issue by bertofer** [mattlewis92/angular-resizable-element#31]
Here's a gif of the behaviour. Looking at the DOM, I can see that when I start moving the mouse, then the property height is set, but not before, which can make a strange visual effect like this one:

![resize problem](https://i.gyazo.com/6f6a1368b72799d283d86d0a9edfb37a.gif)

Kind to do a PR for this 👍

**Comment by mattlewis92** [comment]
Oh that's really odd, feel free to send a PR to fix this! 😃
