### ISSUE TITLE
Keep the resize cursor while the resize is taking place

### ISSUE THREAD

**Issue by bertofer** [mattlewis92/angular-resizable-element#33]
The cursor of the resize appears when hovering over the edge that can be resized, but when you are resizing it should keep it while the resize is taking place.

I'd say this would be the standard behaviour, but it can be done so only happens on enableGhostResize=true (Or even a different input property, though I think it's too much a property just for this). 

Gif to illustrate this behaviour (same as before):

![resize problem](https://i.gyazo.com/6f6a1368b72799d283d86d0a9edfb37a.gif)

**Comment by mattlewis92** [comment]
Makes a lot of sense, would you mind sending a PR for this as well? Should be as simple as  wrapping [this line](https://github.com/mattlewis92/angular-resizable-element/blob/master/src/resizable.directive.ts#L321) with a `if (!currentResize) {}`

**Comment by bertofer** [comment]
I have solved it by assigning cursor to getResizeCursor(currentResize.edges) instead of auto on [this line](https://github.com/mattlewis92/angular-resizable-element/blob/master/src/resizable.directive.ts#L444) 

Preparing PR
