### ISSUE TITLE
table header looses color/style when column resizing

### ISSUE THREAD

**Issue by jtc10005** [mattlewis92/angular-resizable-element#35]
I am not sure if this is an issue or not.  I am using your resize element inside a table header to resize the columns like this...[https://plnkr.co/edit/NTYI3teqwgBjOwF2VhxB?p=preview](https://plnkr.co/edit/NTYI3teqwgBjOwF2VhxB?p=preview)

its work for the most part, but when I click on the resize elements (the right th border) the header looses color/styles.

**Comment by mattlewis92** [comment]
I can't tell you why as I'm no CSS expert but changing the CSS selector to this fixes the problem:
```
.table th {
    background-color: green;
}
```

Fixed plunker: https://plnkr.co/edit/XxWGNfx04z5IEDVZRlY5?p=preview

Hope that helps!
