### ISSUE TITLE
Touch interaction?

### ISSUE THREAD

**Issue by brandonreid** [mattlewis92/angular-resizable-element#36]
Hello,

Wasn't able to find any references in the docs, but is there a way to allow the resizing events to happen on touch from a mobile phone/tablet?

**Comment by mattlewis92** [comment]
Thanks for reporting, it should be fixed now! 😃

**Comment by mattlewis92** [comment]
ps - make sure you're running angular 2.3.1+ for this fix to work

**Comment by brandonreid** [comment]
Thanks @mattlewis92, you're a beast!

**Comment by mattlewis92** [comment]
NP, happy to help! 😄

**Comment by jaredhensley** [comment]
@mattlewis92 is touch still working as of today? I sometimes have trouble "grabbing" onto the edge of an element (using your package to build a resizable split-screen view for teachers).  Thanks boss.

**Comment by mattlewis92** [comment]
@jaredhensley yeah it should do (at least the tests say so). Are you using resize handles rather than the deprecated `resizeEdges` option (which doesn't work that well)

**Comment by jaredhensley** [comment]
@mattlewis92 thanks for the reply mate.  Do you happen to have an example of this implementation? For some reason, I must be overlooking it in the docs.  Much appreciated.

**Comment by mattlewis92** [comment]
If you turn off `enableGhostResize` and implement the resizing of elements manually, then you'll have full control over items being resized and can just set a fixed width of the element being resized, and then resize adjacent elements.
