### ISSUE TITLE
Multiple resizable elements with shared borders?

### ISSUE THREAD

**Issue by fredrik-macrobond** [mattlewis92/angular-resizable-element#38]
Hi Matt,
Thanks for a great gui building tool!

Is it currently possible to have multiple resizable elements with shared borders?
In other words, moving one border would resize two elements.

Thanks,
Fredrik

**Comment by mattlewis92** [comment]
As long as the elements are right next to each other it should work, e.g. https://plnkr.co/edit/XxWGNfx04z5IEDVZRlY5?p=preview
