### ISSUE TITLE
Prerendering from asp.net core fails after adding a dependand module

### ISSUE THREAD

**Issue by scttstrck** [mattlewis92/angular-resizable-element#41]
I'm trying to use angular-calendar in an asp.net core angular2 spa application.
After adding it, I get an error on prerendering which references this module.

Exception: Call to Node module failed with error: Prerendering failed because of error: ReferenceError: MouseEvent is not defined

It seems to be related to the onMousemove functions in resizable.directive.ts and resizeHandle.directive.ts .

I found another project which had apparently the same error:
https://github.com/valor-software/ng2-select/issues/258

**Comment by mattlewis92** [comment]
You can workaround this in your own code by defining it on the global object:

(global as any).MouseEvent = () => {};

**Comment by scttstrck** [comment]
I don't seem to be able to get it to work, but I'll take another look at it tomorrow.

**Comment by mattlewis92** [comment]
Had another look at it this morning and the code doesn't really benefit from MouseEvent being typed so I've just changed it to the any type. Released as 0.6.1.

**Comment by scttstrck** [comment]
Great thanks :) I'll try it out later.

COMPUTERS & LESSONS GmbH
Magnolienweg 12
63741 Aschaffenburg
http://www.comless.de
E-Mail: email@comless.de
Handelsregister Aschaffenburg HRB 5334
Geschäftsführer: Stefan Körbel
Newsletter-Anmeldung: http://www.comless.de/newsletter
