### ISSUE TITLE
Element keeps dragging after mouse up.

### ISSUE THREAD

**Issue by manisabri** [mattlewis92/angular-resizable-element#42]
Hi . 

Not sure if it happened to you too but must be pretty common. I'm using resize validator. The element stops when validator returns false but it keeps moving after I release the mouse button (when I pass over it again).

Thank you,
Mani

Update: I guess passing over an iframe causes this
Update: OK putting an overlay on the iframe solved the problem, its has nothing to do with this package. Thanks again

**Comment by mattlewis92** [comment]
Glad you got it sorted 😄
