### ISSUE TITLE
Resize and keep aspect ratio

### ISSUE THREAD

**Issue by dzena** [mattlewis92/angular-resizable-element#46]
Is it possible to resize the element and respect the aspect ratio?
If not, could we expect the feature to be implemented any day soon?

**Comment by Vi-dot** [comment]
You may use `validateResize` input.
Something like that (Not tested)
```
//template
    <div
      mwlResizable
      (validateResize)="onValidateResize($event)">
    </div>

[...]

onValidateResize(resize: any) {
  let newBoundingRect: BoundingRectangle = resize.rectangle;
  
  // update ratio
  // newBoundingRect.top, newBoundingRect.height ....

  return true;
}
```

**Comment by mattlewis92** [comment]
@Vi-dot is correct in that you can hijack the validate resize function to do this (you'd probably need to tweak the logic a bit more for your apps case but you get the idea), for example: http://plnkr.co/edit/r5GPTah2iKu8wLWRH15g?p=preview

It's not something I would support in the core though as there's too many edge cases to consider e.g. which direction should the element resize in relation too etc
