### ISSUE TITLE
Expose the element that's being resized

### ISSUE THREAD

**Issue by phillip-haydon** [mattlewis92/angular-resizable-element#49]
When the resize event is raised it only gives access to the resize object but does not allow for other arguments or the target element to be passed.

When I've got multiple resize element's I can't know what the current element is being resized. 

Unless of course I'm missing something from the doco, but even when looking at the code only the resize object is emitted. e.g

```
    this.mouseup.subscribe(() => {
      if (currentResize) {
        this.resizeEnd.emit({
          edges: getEdgesDiff({
            edges: currentResize.edges,
            initialRectangle: currentResize.startingRect,
            newRectangle: currentResize.currentRect
          }),
          rectangle: currentResize.currentRect
        });
        removeGhostElement();
        currentResize = null;
      }
    });
```

**Comment by mattlewis92** [comment]
You can access the element that's being resized with the hashtag like so:
```
<div mwlResizable #elm (resizeStart)="onResizeStart($event, elm)"></div>
```

Hope that helps!
