### ISSUE TITLE
Feature: Preserve aspect ratio

### ISSUE THREAD

**Issue by SerhiiTsybulskyi** [mattlewis92/angular-resizable-element#50]
Hello. Could you please add "preserve aspect ratio" option for this module?
For example: https://jqueryui.com/resizable/#aspect-ratio
Thank you for your attention.

**Comment by mattlewis92** [comment]
It's not something I want to support in the core as there are too many edge cases to consider, however you can implement it yourself with the existing API: https://github.com/mattlewis92/angular-resizable-element/issues/46#issuecomment-285719381
