### ISSUE TITLE
Add class to ghost element?

### ISSUE THREAD

**Issue by cmjacques** [mattlewis92/angular-resizable-element#51]
Hi there, thanks for your work on this directive.

Would it be possible to give the ghost element a class so it can be styled differently to the original element?

The style of my resize handle changes on hover (to show the user they can resize the element) but when resizing starts the ghost element replaces the original element and the resize handle is displayed with the original style. 

What I would like is to give the ghost element a class so its resize handle always has the hover state style.

It's a little difficult to describe my use case, so I hope this makes sense.

Thanks!

**Comment by cmjacques** [comment]
I've worked around my "issue" by emitting an event to the parent component. I can then set a class on the parent to achieve what I was after. I do still think adding a class to the ghost element could be useful.

**Comment by mattlewis92** [comment]
I've added this feature in 1.1.0 😄
