### ISSUE TITLE
No worky with flex boxes? [bug/feature request?]

### ISSUE THREAD

**Issue by elliotwesoff** [mattlewis92/angular-resizable-element#53]
Hello,

I've built an application that relies heavily on the use of flex boxes in the layout, but this module doesn't want to work with them. Here's an example in a Plunkr:

https://plnkr.co/edit/00zpy8ZY315sqKevBn02?p=preview

Is there any way to fix this strange behavior? Thanks!

**Comment by mattlewis92** [comment]
Thanks for the plunker, it makes debugging this so much easier! Weirdly if you start dragging the mouse after holding it down it starts working ok which would imply it should be fixable 😄

**Comment by elliotwesoff** [comment]
Yeah it's weird because it resets the size of the boxes on mouse-down, but as soon as you start dragging they go back to normal size.  And then on mouse-up they just snap back to their original position. Idk! :)

**Comment by elliotwesoff** [comment]
So here's what I've got so far (and please correct me if I'm wrong):

The measurements of the resized box - top, bottom, left, right, respectively - are given to the renderer on mouseup (and also when enableGhostResize is true) one by one, and set as CSS properties to that element.   

It seems that due to the nature of flex boxes, the top, bottom, left, and right properties are ignored.  The proper way to adjust the size via flex properties would be to calculate a percentage and set it to the flex-basis property of the target element. But how this would work with adjacent resizable elements like in the Plunkr, I'm not sure. Any ideas?

**Comment by elliotwesoff** [comment]
Actually, I can't even get it to work in the most basic of examples: https://plnkr.co/edit/g9W8fH?p=preview

Am I doing something wrong?

**Comment by mattlewis92** [comment]
It deliberately doesn't save the state of the resize after completion, you have to implement that yourself. Check the demo for how to do this: https://github.com/mattlewis92/angular-resizable-element/blob/master/demo/demo.component.ts#L37
