### ISSUE TITLE
Resize via drag handle not working properly in Firefox

### ISSUE THREAD

**Issue by dev9417** [mattlewis92/angular-resizable-element#54]
Run the demo using Firefox 53.0.3 (32-bit) Windows.
Click on the drag handle and drag to resize.

The box does not look like its resizing as you drag.
Release the mouse and the box resizes to the current location.
However if you continue to move the mouse (with no button pressed) the box keeps resizing as though the handle is still being dragged.
Click once more and the resizing stops.

It works as expected in Chrome, IE, Edge.

**Comment by dyh333** [comment]
yes, I found it too. @mattlewis92  hope fix it.

**Comment by mattlewis92** [comment]
Should be fixed now in 1.1.2, thanks for reporting! 👍
