### ISSUE TITLE
Compile time error, unsupported function call.

### ISSUE THREAD

**Issue by ivws** [mattlewis92/angular-resizable-element#57]
ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an expor
ted function (position 194:50 in the original .ts file), resolving symbol NgModule in E:/ivws/DAM/App/node_modules/angular-resizable-element/node_modules/@angular/core
/core.d.ts

**Comment by mattlewis92** [comment]
It looks like an issue with your build tooling, there is no `core.d.ts` file in this repo: https://unpkg.com/angular-resizable-element@1.2.0/

**Comment by ivws** [comment]
@mattlewis92  Thank you very much for your answer, I hope it can be solved.
