### ISSUE TITLE
select tag doesnt work correctly when resizing

### ISSUE THREAD

**Issue by simonmetria** [mattlewis92/angular-resizable-element#58]
If you add a select tag with more than one option inside the resizable div and you select the second option (or make it selected by default), the first option gets selected while resizing and when you stop resizing the second option gets selected back again.

**Comment by mattlewis92** [comment]
I'm guessing you're using the `enableGhostResize` input? It works by [cloning the html element](https://github.com/mattlewis92/angular-resizable-element/blob/master/src/resizable.directive.ts#L484-L496) hence the behaviour you're seeing will be messing up angulars form controls. It works for a majority of use cases but in instances like this you'll need to not enable it and implement the ghost resizing logic yourself using the `resizeStart` / `resizing` and `resizeEnd` events.

**Comment by simonmetria** [comment]
Ah ok, I see. Thanks for the reply!
