### ISSUE TITLE
After clicking on resize 2 pixels added to width and height

### ISSUE THREAD

**Issue by TomRed97** [mattlewis92/angular-resizable-element#61]
After only clicking not resizing - 2 pixels were added to width and height always.
After resizing only width 2 pixels default were added to height.
I think it's a bug.

**Comment by mattlewis92** [comment]
I can't reproduce this on the demo, can you make a plunker or something that reproduces your issue? Thanks!

**Comment by TomRed97** [comment]
Thanks.
[https://plnkr.co/edit/3FGIfI1DDql425QX7hjd?p=preview] 
That is

**Comment by mattlewis92** [comment]
Ah it looks like it's caused by not using bootstrap which adds box-sizing to all elements. Adding this snippet of CSS should fix the problem for you:
```
mwlResizable {
  box-sizing: border-box;
}
```

**Comment by TomRed97** [comment]
Thank you
