### ISSUE TITLE
Div is resizable but when resize ends, it is resizable to default div.

### ISSUE THREAD

**Issue by sdhotre** [mattlewis92/angular-resizable-element#67]
I have used [resizeEdges]="{bottom: true, right: true, top: true, left: true}" [resizeSnapGrid]="{right: 10}" but still not working

**Comment by mattlewis92** [comment]
That's the expected behaviour, it's up to you to persist the actual resizing of the div. Check out the demo for an example of how to do this: https://github.com/mattlewis92/angular-resizable-element/blob/master/demo/demo.component.ts#L59-L66

**Comment by sdhotre** [comment]
Hello,

Thanks Matt ☺
