### ISSUE TITLE
resizable undefined after enabling handles via *ngIf

### ISSUE THREAD

**Issue by SebastianStumm** [mattlewis92/angular-resizable-element#68]
I've encountered a Problem with the handles **only** when disabling them and enabling them after a button was clicked.
I tried this in the simplest way possible with:

```
<div mwlResizable>
    <div mwlResizeHandle [resizeEdges]="{bottom: true, right: true}" *ngIf="enabled">#</div>
</div>
.....
<button (click)="enable()">Enable Handle</button>
```

If i activate the div's handle with the button i get the following error:

> ERROR TypeError: _this.resizable is undefined
Stack-Trace:
../../../../angular-resizable-element/dist/esm/src/resizeHandle.directive.js/ResizeHandle.prototype.onMouseup/<@http://localhost:4200/vendor.bundle.js:701:13
../../../../zone.js/dist/zone.js/</</ZoneDelegate.prototype.invoke@http://localhost:4200/polyfills.bundle.js:2937:17
../../../../zone.js/dist/zone.js/</</Zone.prototype.run@http://localhost:4200/polyfills.bundle.js:2687:24
../../../core/@angular/core.es5.js/</NgZone.prototype.runOutsideAngular@http://localhost:4200/vendor.bundle.js:110780:68
../../../../angular-resizable-element/dist/esm/src/resizeHandle.directive.js/ResizeHandle.prototype.onMouseup@http://localhost:4200/vendor.bundle.js:699:9
View_GridComponent_1/<@ng:///AppModule/GridComponent.ngfactory.js:31:19
handleEvent@http://localhost:4200/vendor.bundle.js:118950:98
callWithDebugContext@http://localhost:4200/vendor.bundle.js:120411:39
debugHandleEvent@http://localhost:4200/vendor.bundle.js:119999:12
dispatchEvent@http://localhost:4200/vendor.bundle.js:115543:12
renderEventHandlerClosure/<@http://localhost:4200/vendor.bundle.js:116154:20
decoratePreventDefault/<@http://localhost:4200/vendor.bundle.js:133046:53
../../../../zone.js/dist/zone.js/</</ZoneDelegate.prototype.invokeTask@http://localhost:4200/polyfills.bundle.js:2970:17
onInvokeTask@http://localhost:4200/vendor.bundle.js:110817:24
../../../../zone.js/dist/zone.js/</</ZoneDelegate.prototype.invokeTask@http://localhost:4200/polyfills.bundle.js:2969:17
../../../../zone.js/dist/zone.js/</</Zone.prototype.runTask@http://localhost:4200/polyfills.bundle.js:2737:28
../../../../zone.js/dist/zone.js/</</ZoneTask.invokeTask@http://localhost:4200/polyfills.bundle.js:3044:24
invokeTask@http://localhost:4200/polyfills.bundle.js:3972:9
globalZoneAwareCallback@http://localhost:4200/polyfills.bundle.js:3990:17

Maybe you have a clue why this happens or if im using the handles incorrect.

edit:
After some testing im sure the handles have no resizable object anymore after disabling them with *ngIf.

**Comment by mattlewis92** [comment]
Ah, it's because the handles are linked to the parent only once when the parent is created: https://github.com/mattlewis92/angular-resizable-element/blob/master/src/resizable.directive.ts#L532-L536. Using `this.resizeHandles.changes.subscribe()` instead to re-initialise the directive should fix the issue. The workaround for now is to use `[hidden]` instead to not destroy the resize handles.

**Comment by SebastianStumm** [comment]
Thank you for your fast awnser! The [hidden] method works fine, just had to capsule my icons in another div.

**Comment by seekheart** [comment]
you could also try using `ng-container` to contain the structural directive `*ngIf`

**Comment by SebastianStumm** [comment]
no ng-container would not work since this would only move the problem from the single handle to the container of the handles. The *ngIf directive would destroy all elements in the ng-container. The hidden method works fine if the handle does not have any display style attached to it. And the solution if you need to use *ngIf is, as matt already stated, to subscribe to the handles collection and to re-initialise it on change.
