### ISSUE TITLE
Error when resizing nested element, all the elements will resize  once hit by mouseover

### ISSUE THREAD

**Issue by shrwn14** [mattlewis92/angular-resizable-element#69]
should have an option to stop propagation (something like e.stopPropagation())  when element are on top of each other.

**Comment by mattlewis92** [comment]
This is actually by design so that elements that are next to each other can be resized:

<img src="https://media.giphy.com/media/xULW8HGVOsrpiXP4GI/giphy.gif">

Happy to debug more if you can put together a minimal repro via stackblitz etc that reproduces your problem. Thanks! 😄
