### ISSUE TITLE
Onresizing a div outside its edge, resize cursor changing to default cursor

### ISSUE THREAD

**Issue by Anki1611** [mattlewis92/angular-resizable-element#70]
Hi,
The cursor of the resize appears when hovering/resizing over the edge that can be resized, but when you coming out of the edge and still resizing outside the edge, the resize cursor is changing to default cursor.

**Comment by SebastianStumm** [comment]
I also noticed this and made a simple workaround. You can change the cursor in the resizeStart method and change it back in the resizeEnd method.

in the .html file:
`<div #tile mwlResizable (resizeStart)="onResizeStart($event, tile)" (resizeEnd)="onResizeEnd($event, tile)"[enableGhostResize]="true"></div>`

in the .ts class:
```
onResizeStart(event: ResizeEvent, tile: any) {
    let body = document.getElementsByTagName('body')[0];
    body.style.cursor = tile.children[1].style.cursor;
  }
```
```
onResizeEnd(event: ResizeEvent, tile: any) {
    let body = document.getElementsByTagName('body')[0];
    body.style.cursor = '';
  }
```
