### ISSUE TITLE
Support for Angular 5+

### ISSUE THREAD

**Issue by tonnguyen** [mattlewis92/angular-resizable-element#75]
This is a feature request
Additional Notes:

Currently this project does not support Angular 5.0. A build warning appear:
warning "angular-resizable-element@1.2.1" has incorrect peer dependency "@angular/core@^4.0.0".

Is there any pre-release that does?

What do we need to change to implement the support?

**Comment by mattlewis92** [comment]
You need to upgrade to 1.2.4 where the peer dependency is fixed 😄  https://github.com/mattlewis92/angular-resizable-element/blob/master/CHANGELOG.md#124-2017-10-21

**Comment by tonnguyen** [comment]
Thank you!
