### ISSUE TITLE
Combine with bootstrap 3.3.7 or 4

### ISSUE THREAD

**Issue by xino1010** [mattlewis92/angular-resizable-element#78]
I would like to use this plugin to change the size of the bootstrap columns. Is it possible?
I have been proving to change container (works) but only change its witdh/height not the others...

**Comment by mattlewis92** [comment]
Bootstrap columns are based on percentages related to the parent container, and this lib is primarily for fixed element resizing rather than percentages so I'm not too sure it would work that well.
