### ISSUE TITLE
Flatten ESM build for server-side rendering

### ISSUE THREAD

**Issue by laurentgoudet** [mattlewis92/angular-resizable-element#79]
Currently `angular-resizable-element` breaks when used on the server-side as explained in https://github.com/angular/angular-cli/issues/7200. In short, when targeting the `server` platform  with the Angular CLI only the app itself is compiled, as the libraries' UMD bundles would then be used when running it in NodeJS. However, when said library is published at separate ES modules instead of a flatten one (FESM), the deep imports would then resolved to the ES modules (and not the UMD bundle) on the server-side, causing Node to fail as it doesn't understand ES modules (`v8.5` does with a special flag, but only with the `.mjs` file extension):

```
/foo/node_modules/angular-resizable-element/dist/esm/src/resizable.directive.js:1
(function (exports, require, module, __filename, __dirname) { import { Directive, Renderer2, ElementRef, Output, Input, EventEmitter, ContentChildren, NgZone } from '@angular/core';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:588:28)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.angular-resizable-element/dist/esm/src/resizable.directive (/foo/universal/dist/main.bundle.js:31258:18)
```

Flattening the ESM output fixes that, and is also a best practice as per the [Angular Package Format guidelines](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview) as it allows for faster builds, and makes sure that private imports aren't being used.

**Comment by mattlewis92** [comment]
Hey, so sorry about the late reply on this one, I've not had much time for open source lately. I've gone with ng-packagr in the end as it allows loads of build tooling to be deleted and follows the angular package guidelines. Am just cutting 2.0 now with the changes. Thanks for your contribution! 😄
