### ISSUE TITLE
Question: Is possible to increase the mouse detection in the border

### ISSUE THREAD

**Issue by abnersouza** [mattlewis92/angular-resizable-element#81]
The resize is working fine, but I when i set a zoom to the page using css it stops working.

Do you have any idea how could i fix it.

**Comment by mattlewis92** [comment]
It is [not recommended](https://css-tricks.com/almanac/properties/z/zoom/) to use the CSS zoom property in production sites so it's not something that I can ever see working with this module. Sorry I couldn't be of more help!
