### ISSUE TITLE
Treat Document Level Touch Event Listeners as Passive

### ISSUE THREAD

**Issue by jaredhensley** [mattlewis92/angular-resizable-element#96]
https://www.chromestatus.com/features/5093566007214080

console throws errors in chrome developer tools due to the change from above.

error throw:

Unable to preventDefault inside passive event listener due to target being treated as passive.

I believe we need to check for event.type !== "touchmove" || "touchstart" on line 440 in resizable.directive.ts

I can open a pull request for this. Thoughts?

**Comment by mattlewis92** [comment]
Yeah please send a PR, I'm not sure if `passive: true` would break things though, maybe it's better to instead explicitly set `passive: false` on the touch listeners
